<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Employee;
use Illuminate\Support\Str;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employees = [
            [
                'employee_id' => 'EMP001',
                'name' => 'Ahmad Rizki Pratama',
                'position' => 'Software Developer',
                'department' => 'IT',
                'hire_date' => '2023-01-15',
                'phone' => '081234567890',
                'email' => 'ahmad.rizki@company.com',
                'status' => 'active',
                'photo' => null,
            ],
            [
                'employee_id' => 'EMP002',
                'name' => 'Siti Nurhaliza',
                'position' => 'HR Manager',
                'department' => 'Human Resources',
                'hire_date' => '2022-08-10',
                'phone' => '081987654321',
                'email' => 'siti.nurhaliza@company.com',
                'status' => 'active',
                'photo' => null,
            ],
            [
                'employee_id' => 'EMP003',
                'name' => 'Budi Santoso',
                'position' => 'Finance Manager',
                'department' => 'Finance',
                'hire_date' => '2021-03-22',
                'phone' => '082123456789',
                'email' => 'budi.santoso@company.com',
                'status' => 'active',
                'photo' => null,
            ],
            [
                'employee_id' => 'EMP004',
                'name' => 'Dewi Kartika',
                'position' => 'Marketing Specialist',
                'department' => 'Marketing',
                'hire_date' => '2023-05-18',
                'phone' => '083456789012',
                'email' => 'dewi.kartika@company.com',
                'status' => 'active',
                'photo' => null,
            ],
            [
                'employee_id' => 'EMP005',
                'name' => 'Andi Wijaya',
                'position' => 'Operations Manager',
                'department' => 'Operations',
                'hire_date' => '2020-11-05',
                'phone' => '084567890123',
                'email' => 'andi.wijaya@company.com',
                'status' => 'active',
                'photo' => null,
            ],
            [
                'employee_id' => 'EMP006',
                'name' => 'Maya Sari',
                'position' => 'UI/UX Designer',
                'department' => 'IT',
                'hire_date' => '2023-02-14',
                'phone' => '085678901234',
                'email' => 'maya.sari@company.com',
                'status' => 'active',
                'photo' => null,
            ],
            [
                'employee_id' => 'EMP007',
                'name' => 'Rudi Hermawan',
                'position' => 'System Analyst',
                'department' => 'IT',
                'hire_date' => '2022-07-20',
                'phone' => '086789012345',
                'email' => 'rudi.hermawan@company.com',
                'status' => 'active',
                'photo' => null,
            ],
            [
                'employee_id' => 'EMP008',
                'name' => 'Lina Marlina',
                'position' => 'Accountant',
                'department' => 'Finance',
                'hire_date' => '2021-12-08',
                'phone' => '087890123456',
                'email' => 'lina.marlina@company.com',
                'status' => 'active',
                'photo' => null,
            ],
            [
                'employee_id' => 'EMP009',
                'name' => 'Fajar Nugroho',
                'position' => 'Sales Executive',
                'department' => 'Marketing',
                'hire_date' => '2023-04-12',
                'phone' => '088901234567',
                'email' => 'fajar.nugroho@company.com',
                'status' => 'active',
                'photo' => null,
            ],
            [
                'employee_id' => 'EMP010',
                'name' => 'Rina Susanti',
                'position' => 'HR Specialist',
                'department' => 'Human Resources',
                'hire_date' => '2022-09-30',
                'phone' => '089012345678',
                'email' => 'rina.susanti@company.com',
                'status' => 'active',
                'photo' => null,
            ],
            [
                'employee_id' => 'EMP011',
                'name' => 'Doni Prasetyo',
                'position' => 'Database Administrator',
                'department' => 'IT',
                'hire_date' => '2021-06-15',
                'phone' => '081123456789',
                'email' => 'doni.prasetyo@company.com',
                'status' => 'active',
                'photo' => null,
            ],
            [
                'employee_id' => 'EMP012',
                'name' => 'Indah Permata',
                'position' => 'Content Creator',
                'department' => 'Marketing',
                'hire_date' => '2023-03-25',
                'phone' => '082234567890',
                'email' => 'indah.permata@company.com',
                'status' => 'active',
                'photo' => null,
            ],
            [
                'employee_id' => 'EMP013',
                'name' => 'Hendra Gunawan',
                'position' => 'Quality Assurance',
                'department' => 'IT',
                'hire_date' => '2022-11-18',
                'phone' => '083345678901',
                'email' => 'hendra.gunawan@company.com',
                'status' => 'active',
                'photo' => null,
            ],
            [
                'employee_id' => 'EMP014',
                'name' => 'Putri Anggraini',
                'position' => 'Financial Analyst',
                'department' => 'Finance',
                'hire_date' => '2021-10-07',
                'phone' => '084456789012',
                'email' => 'putri.anggraini@company.com',
                'status' => 'active',
                'photo' => null,
            ],
            [
                'employee_id' => 'EMP015',
                'name' => 'Agus Setiawan',
                'position' => 'Operations Supervisor',
                'department' => 'Operations',
                'hire_date' => '2020-08-14',
                'phone' => '085567890123',
                'email' => 'agus.setiawan@company.com',
                'status' => 'active',
                'photo' => null,
            ],
            [
                'employee_id' => 'EMP016',
                'name' => 'Novi Rahayu',
                'position' => 'Project Manager',
                'department' => 'IT',
                'hire_date' => '2021-04-28',
                'phone' => '086678901234',
                'email' => 'novi.rahayu@company.com',
                'status' => 'active',
                'photo' => null,
            ],
            [
                'employee_id' => 'EMP017',
                'name' => 'Bayu Firmansyah',
                'position' => 'Digital Marketing',
                'department' => 'Marketing',
                'hire_date' => '2023-01-09',
                'phone' => '087789012345',
                'email' => 'bayu.firmansyah@company.com',
                'status' => 'active',
                'photo' => null,
            ],
            [
                'employee_id' => 'EMP018',
                'name' => 'Citra Dewi',
                'position' => 'Administrative Assistant',
                'department' => 'Human Resources',
                'hire_date' => '2022-12-03',
                'phone' => '088890123456',
                'email' => 'citra.dewi@company.com',
                'status' => 'active',
                'photo' => null,
            ],
            [
                'employee_id' => 'EMP019',
                'name' => 'Rizal Maulana',
                'position' => 'Network Administrator',
                'department' => 'IT',
                'hire_date' => '2021-09-16',
                'phone' => '089901234567',
                'email' => 'rizal.maulana@company.com',
                'status' => 'active',
                'photo' => null,
            ],
            [
                'employee_id' => 'EMP020',
                'name' => 'Yuni Astuti',
                'position' => 'Customer Service',
                'department' => 'Operations',
                'hire_date' => '2023-06-21',
                'phone' => '081012345678',
                'email' => 'yuni.astuti@company.com',
                'status' => 'inactive',
                'photo' => null,
            ],
        ];

        foreach ($employees as $employee) {
            Employee::create([
                'id' => Str::uuid(),
                'name' => $employee['name'],
                'position' => $employee['position'],
                'department' => $employee['department'],
                'hire_date' => $employee['hire_date'],
                'phone' => $employee['phone'],
                'email' => $employee['email'],
                'status' => $employee['status'],
                'photo' => $employee['photo'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
